### ISSUE TITLE
(URGENT) Build failing for macOS and Ubuntu (passing on Windows) from dispatch

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-ogc#31]
https://github.com/metanorma/mn-templates-ogc/actions/runs/270934774

**Comment by ronaldtse** [comment]
```
Creating test/standard/figures/README.adoc
304
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.5.3/lib/asciidoctor/standoc/front_contributor.rb:32:in `block in csv_split': undefined method `strip' for nil:NilClass (NoMethodError)
305
	from /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.5.3/lib/asciidoctor/standoc/front_contributor.rb:32:in `map'
306
	from /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.5.3/lib/asciidoctor/standoc/front_contributor.rb:32:in `csv_split'
307
	from /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-ogc-1.2.3/lib/asciidoctor/ogc/front.rb:15:in `corporate_author'
308
	from /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-ogc-1.2.3/lib/asciidoctor/ogc/front.rb:9:in `metadata_author'
309
	from /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.5.3/lib/asciidoctor/standoc/front.rb:142:in `metadata'
310
	from /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.5.3/lib/asciidoctor/standoc/base.rb:178:in `block in front'
311
	from /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
312
	from /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
313
```

**Comment by CAMOBAP** [comment]
The issue clearly in metanorma-standoc module, looks like it was released 12h ago let me rerun it

**Comment by ronaldtse** [comment]
Latest build is still failing.

**Comment by ronaldtse** [comment]
Fixed by @CAMOBAP , thanks!
